language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - '7'
mysql:
  database: activecollab_database_connection_test
  username: root
  encoding: utf8mb4
install: composer install --dev
before_script:
  # create the database
  - mysql -e 'create database activecollab_database_connection_test'
script: phpunit -c test/phpunit.xml