sudo: true
language: php
php:
  - 7.1
services:
  - mysql
install: composer install --dev
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'create database activecollab_database_connection_test'
script: vendor/bin/phpunit
